# This file was generated by the `rails generate rspec:install` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# The generated `.rspec` file contains `--require spec_helper` which will cause
# this file to always be loaded, without a need to explicitly require it in any
# files.
#
require 'factory_bot'
require 'faker'
# spec_helper.rb

require 'mongoid-rspec'

RSpec.configure do |config|
  config.include Mongoid::Matchers
end
